go.mod, go.sum, sonar-project.properties
Please include a summary of the change and why it is needed.
Fixes # (issue)
Add any other context or screenshots about the feature request here.
=> chore: Migrate from gerrit to github pipelines

.github/workflows/codeql.yaml
Use Go 1.22 for CodeQL.
Fixes #58 
=> chore: Set Go 1.22 for CodeQL

controllers/integrationsecret/integrationsecret_controller.go, controllers/integrationsecret/integrationsecret_controller_test.go
Process secrets for GitHub Packages and set the correct status
Fixes #63 
Added unit test and manual testing locally.
=> feat: Process integration secret status for ghrc

controllers/codebasebranch/codebasebranch_controller.go, controllers/codebasebranch/codebasebranch_controller_test.go
The codebase-operator is designed to automate branch creation in a Git repository. However, when GitHub's branch creation rules prevent the creation of a branch, the codebase-operator still reports the status of the codebasebranch Custom Resource (CR) as successful. This behavior is misleading and can cause confusion, as the branch has not actually been created successfully.
Fixes #65 
Added unit test.
=> fix: Enable failed status for CodebaseBranch

controllers/codebasebranch/chain/put_branch_in_git/put_branch_in_git.go, controllers/codebasebranch/chain/put_branch_in_git/put_branch_in_git_test.go
This change fixes the incorrect status of the branch if the push to the remote repository fails.
The issue was with the local working git repository. If the push to the remote repository fails,
the second reconciliation succeeds because the local branch is created, and the operator doesn't check whether the remote branch exists. Added a step to clean the git working directory in case the push fails.
Fixes #65 
=> fix: Set CodebaseBranch failed status

build/templates/applications/helm-chart/kubernetes/README.tmpl
=> fix: Fix helm-docs for new helm-chart (#68)

build/templates/applications/helm-chart/kubernetes/README.tmpl
=> fix: Align helm-docs to the latest changes (#68)

api/v1/cdstagedeploy_types.go, config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml, deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml, docs/api.md
Set default pending status for CDStageDeploy.
Fixes #71 
Manual testing.
=> fix: Set default pending status for CDStageDeploy

deploy-templates/templates/clusterrole_openshift.yaml, deploy-templates/templates/clusterrolebinding_openshift.yaml, deploy-templates/templates/role_openshift.yaml, deploy-templates/templates/rolebinding_admin_openshift.yaml, deploy-templates/templates/rolebinding_openshift.yaml
=> chore: Update argocd diff

build/templates/applications/helm-chart/kubernetes/templates/ingress.yaml
Please include a summary of the change and why it is needed.
Fixes # (GitHub Issue)
Add any other context or screenshots about the feature request here.
=> fix: Deploy pipeline is failed if deploy with ingress 

.github/workflows/codecov.yaml, .github/workflows/codeql.yaml
=> chore: Update codeql and codecov scan gh actions (#83)

controllers/integrationsecret/integrationsecret_controller.go, controllers/integrationsecret/integrationsecret_controller_test.go
Added annotation to the secret with the status ok/error for the given credentials.
Fixes #86
Unit tests. Manual testing.
=> feat: Add status for Codemie secret

controllers/gitserver/create_event_listener.go
=> fix: Update EventListener name to include edp prefix (#83)

controllers/gitserver/create_event_listener.go
We have 'edp' prefix in the EventListener
#83
=> fix: Fix service name for the ingress (#83)

controllers/gitserver/create_event_listener.go, controllers/gitserver/create_event_listener_test.go
Add check for EventListener creation.
Fixes #83 
Unit tests.
=> test: Add check for EventListener creation

controllers/gitserver/create_event_listener.go
Fix hard-coded EventListener name.
Fixes #83 
Unit tests.
=> refactor: Fix hard-coded EventListener name

controllers/codebasebranch/chain/put_codebase_image_stream/put_codebase_image_stream.go, controllers/codebasebranch/chain/put_codebase_image_stream/put_codebase_image_stream_test.go
Add CodebaseBranch as a controller reference for the related CodebaseImageStream.
This change ensures that CodebaseImageStream is automatically removed when CodebaseBranch is deleted,
helping to avoid storing outdated CodebaseImageStreams.
Fixes #97 
- Unit tests
- Manual testing
Add any other context or screenshots about the feature request here.
=> feat: Remove CodebaseImageStream if CodebaseBranch is removed

controllers/jiraserver/jiraserver_controller.go
There is an issue with the current Jira user login approach. Even with the correct username and password, a 401 error code is returned in the JiraServer Custom Resource (CR). This needs to be investigated and fixed to ensure proper authentication.
Fixes #103 
Manual testing.
=> fix: 401 error for correct username and password in JiraServer

controllers/integrationsecret/integrationsecret_controller.go, controllers/integrationsecret/integrationsecret_controller_test.go
This change fixes the checking of sonar credentials.
Fixes #105 
- Unit tests
- Manual testing
=> fix: Integration secret shows connected status for invalid credentials

controllers/integrationsecret/integrationsecret_controller.go
Integration secret shows connected status for invalid credentials
Fixes #105 
- Manual testing.
=> fix: Dependency-Track secret shows connected status for invalid credentials

api/v1/cdstagedeploy_types.go, config/crd/bases/v2.edp.epam.com_cdstagedeployments.yaml, deploy-templates/crds/v2.edp.epam.com_cdstagedeployments.yaml
Create printcolumn for CDStageDeploy object.
Issue: #116 
deployed in tests
N/A
N/A
=> chore: Add printcolumn for CDStageDeploy object (#116)

controllers/codebase/service/template/template.go, pkg/util/template.go, pkg/util/template_test.go
- Add default template files for RPM if a language is not supported.
- Update the operator to create Makefile.kuberocketci if a Makefile already exists.
Fixes #123 
- Unit tests
- Manual testing
=> feat: Implement fallback strategy for RPM packaging

deploy-templates/templates/role_openshift.yaml, deploy-templates/templates/rolebinding_admin_openshift.yaml, deploy-templates/templates/rolebinding_openshift.yaml
Change apiVersion field for OKD RBAC resources to "rbac.authorization.k8s.io/v1"
Fixes #74
=> chore: Change apiVersion for OKD RBAC resources (#76)

Dockerfile, controllers/integrationsecret/integrationsecret_controller.go, controllers/integrationsecret/integrationsecret_controller_test.go
Align codemie secret label
Related Issue #86
=> Fix genai chat secret

deploy-templates/templates/role_openshift.yaml, deploy-templates/templates/rolebinding_admin_openshift.yaml, deploy-templates/templates/rolebinding_openshift.yaml
Align argo-cd diff for OKD RBAC resources
Fixes #76
=> chore: Align argo-cd diff for OKD resources (#76)

CHANGELOG.md
This change updates the CHANGELOG.md file with the contents generated by the "make changelog" command.
=> docs: Update CHANGELOG md (#129)

CHANGELOG.md
This change updates the CHANGELOG.md file
=> docs: Update changelog file for release notes (#136)

Dockerfile, deploy-templates/Chart.yaml
Updated alpine base image to v3.18.9
Fixes #141
=> chore: Update alpine base image to v3.18.9 (#141)

controllers/codebase/service/chain/put_project.go, pkg/gitprovider/bitbucket.go, pkg/gitprovider/bitbucket_test.go, pkg/gitprovider/errors.go, pkg/gitprovider/gitlab.go
Add support for clone/create strategy for Bitbucket.
Fixes #143 
- Unit tests
=> feat: Add support of clone/create strategy for Bitbucket

build/templates/applications/rpm-package/Makefile.tmpl
=> chore: Add set version block

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#150)

pull_request_template.md
Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #21
=> chore: Update Pull Request Template (#21)

controllers/codebaseimagestream/chain/put_cd_stage_deploy.go, controllers/codebaseimagestream/chain/put_cd_stage_deploy_test.go
=> fix: Ignore extra labels in CodebaseImageStream for auto-deploy (#153)

CHANGELOG.md, deploy-templates/Chart.yaml
=> chore: Update current development version (#158)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#166)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#170)

main.go
Update Telemetry endpoint to https://telemetry.kuberocketci.io.
Fixes #174
=> chore: Update Telemetry endpoint (#174)

deploy-templates/templates/validation_webhook.yaml
Missing namespace selector for codebaseimagestream webhook 
Fixes #176 
- Manual testing
=> fix: Missing namespace selector for codebaseimagestream webhook (#176)

api/v1/codebase_types.go, controllers/codebasebranch/chain/process_new_version.go, controllers/codebasebranch/chain/process_new_version_test.go, controllers/codebasebranch/chain/put_branch_in_git/put_branch_in_git_test.go, controllers/codebasebranch/codebasebranch_controller.go, controllers/codebasebranch/codebasebranch_controller_test.go, pkg/webhook/validation_test.go, pkg/webhook/webhook_suite_test.go
Rename platform versioning from edp to semver
Fixes #179 
- Unit tests
=> feat: Rename platform versioning from edp to semver

api/v1/codebase_types.go, config/crd/bases/v2.edp.epam.com_codebases.yaml, controllers/codebase/service/chain/put_project.go, controllers/codebase/service/chain/put_project_test.go, deploy-templates/crds/v2.edp.epam.com_codebases.yaml, docs/api.md, pkg/gitprovider/bitbucket.go, pkg/gitprovider/bitbucket_test.go, pkg/gitprovider/github.go, pkg/gitprovider/github_test.go, pkg/gitprovider/gitlab.go, pkg/gitprovider/gitlab_test.go, pkg/gitprovider/mocks/gitprojectprovider_mock.go, pkg/gitprovider/provider.go
Please include a summary of the change and why it is needed.
Fixes #(issue)
- Unit tests
=> feat: Add support for private repository creation (#181)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#187)

deploy-templates/README.md, deploy-templates/templates/deployment.yaml, deploy-templates/values.yaml
Add ImagePullSecrets field support in the Helm chart
Fixes #190
=> chore: Add ImagePullSecrets field support (#190)

CHANGELOG.md, deploy-templates/Chart.yaml
=> chore: Update current development version (#192)

api/v1/labels.go, controllers/codebasebranch/chain/put_codebase_image_stream/put_codebase_image_stream.go, controllers/codebasebranch/chain/put_codebase_image_stream/put_codebase_image_stream_test.go, controllers/codebasebranch/codebasebranch_controller_test.go, pkg/autodeploy/autodeploy_test.go, pkg/codebasebranch/labels.go, pkg/codebaseimagestream/codebaseimagestream.go, pkg/codebaseimagestream/codebaseimagestream_test.go
Update codebase and codebasebranch label to improve consistency
Fixes #198
-unit tests
=> refactor: Update codebase and codebasebranch label to improve consistency

api/v1/labels.go, controllers/codebasebranch/codebasebranch_controller_test.go, pkg/codebasebranch/labels.go, pkg/codebasebranch/labels_test.go
"app.edp.epam.com/codebasebranch-git-branch" - we can use this label to filter by the associated Git branch
Fixes #198
- Unit tests
=> feat: Add labels for CodebaseBranch

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#217)
